### ISSUE TITLE
GrinBOX-SRS-submission

### ISSUE THREAD

**Issue by avigailab** [avigailab/GrinBOX#1]
SRS Document: https://github.com/avigailab/GrinBOX/blob/master/doc/GrinBOX-SRS.docx
Git Code: https://github.com/avigailab/GrinBOX
Wiki: https://github.com/avigailab/GrinBOX/wiki
Distribution:http://grinbox.azurewebsites.net

**Comment by robi-y** [comment]
@hadarp will close it

**Comment by hadarp** [comment]
Checked

**Comment by robi-y** [comment]
please re-check
